on:
  push:
  workflow_dispatch:

jobs:
  test-timeout:
    name: ${{ matrix.package-version }} (${{ matrix.os }}/py${{ matrix.python-version }}/${{ matrix.dependencies }}/sslfix=${{ matrix.use-ssl-fix }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
        python-version:
          - '3.6'
          - '3.7'
          - '3.8'
          - '3.9'
        package-version:
          - '3.7.6'
          - '3.7.7'
        dependencies:
          - ''
          - -r mpcontribs-client/requirements.txt
        use-ssl-fix:
          - ''
          - 'true'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install build dependencies
        shell: bash
        run: |
          python -m pip install --upgrade --quiet pip setuptools wheel
      - name: pip debug
        shell: bash
        run: |
          python -m pip debug -v
      - name: Install requirements
        if: contains(matrix.dependencies, 'requirements.txt')
        shell: bash
        run: |
          python -m pip install --progress-bar=off ${{ matrix.dependencies }}
      - name: Install mpcontribs-client
        shell: bash
        run: |
          python -m pip install --progress-bar=off mpcontribs-client==${{ matrix.package-version }}
      - name: pip list
        shell: bash
        run: |
          python -m pip list
      - name: Run minimal example
        shell: bash
        env:
          MPCONTRIBS_API_KEY: ${{ secrets.MPCONTRIBS_API_KEY }}
          USE_SSL_FIX:  ${{ matrix.use-ssl-fix }}
        run: |
          python -c '
          import os
          import sys

          USE_SSL_FIX = bool(os.environ.get("USE_SSL_FIX", ""))
          
          if sys.platform.startswith("win") and USE_SSL_FIX:
              import certifi
              os.environ["SSL_CERT_FILE"] = certifi.where()

          from mpcontribs.client import Client

          API_KEY = os.environ.get("MPCONTRIBS_API_KEY")
          c = Client(apikey=API_KEY)
          print(c)
          '