on:
  push:
  workflow_dispatch:

jobs:
  test-timeout:
    name: ${{ matrix.client-package }} (${{ matrix.os }}/py${{ matrix.python-version }}/${{ matrix.dependencies }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest
        python-version:
          - '3.6'
          - '3.7'
          - '3.8'
          - '3.9'
        client-package:
          - mpcontribs-client==3.7.6
          - mpcontribs-client==3.7.7
        dependencies:
          - ''
          - -r mpcontribs-client/requirements.txt
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install build dependencies
        shell: bash
        run: |
          python -m pip install --upgrade --quiet pip setuptools wheel
      - name: Install requirements
        if: contains(matrix.dependencies, 'requirements.txt')
        shell: bash
        run: |
          python -m pip install --progress-bar=off ${{ matrix.dependencies }}
      - name: Install mpcontribs-client
        shell: bash
        run: |
          python -m pip install --progress-bar=off ${{ matrix.client-package }}
      - name: Run minimal example
        shell: bash
        env:
          MPCONTRIBS_API_KEY: ${{ secrets.MPCONTRIBS_API_KEY }}
        run: |
          python -c '
          import os
          from mpcontribs.client import Client

          API_KEY = os.environ.get("MPCONTRIBS_API_KEY")
          c = Client(apikey=API_KEY)
          print(c)
          '