name: test and release

on:
  push:
    branches:
      - master
    tags:
      - "*.*.*"
    paths:
      - mpcontribs-client/**
  pull_request:
    branches:
      - master
    paths:
      - mpcontribs-client/**

jobs:
  test:
    name: ${{ matrix.client-package }} (${{ matrix.os }}/py${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']
        python-version: ['3.7', '3.8', '3.9']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions setuptools wheel
    - name: Test client with tox
      env:
        MPCONTRIBS_API_KEY: ${{ secrets.MPCONTRIBS_API_KEY }}
      run: |
        cd mpcontribs-client
        tox

  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel
        cd mpcontribs-client
        python setup.py sdist --dist-dir ../dist
        python setup.py bdist_wheel --dist-dir ../dist
    - name: Publish distribution 📦s to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        skip_existing: true
        password: ${{ secrets.test_pypi_password }}
        repository_url: https://test.pypi.org/legacy/
    - name: Publish distribution 📦 to PyPI
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.pypi_password }}
